version: 666.{build}
skip_tags: false
os: Visual Studio 2017
clone_depth: 1
clone_folder: C:\rssguard

environment:
  QTDIR: 'C:\Qt\5.12\msvc2017_64'
  QMAKESPEC: win32-msvc
  COMPILERBAT: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"'
  access_token:
    secure: oR2iY1h+Z5AF4t3yP1mxNW7HL8qhPm8y4Uupp4b03QSC7puVrkkCaO1E1NQA9q9K
  matrix:
    - qmake_args: 'USE_WEBENGINE=false'
    - qmake_args: 'USE_WEBENGINE=true'

artifacts:
  - path: 'rssguard-build\*win64.exe'
    name: rssguardexe

  - path: 'rssguard-build\*win64.7z'
    name: rssguard7z

deploy:
  description: 'release by appveyor'
  provider: GitHub
  auth_token:
    secure: oR2iY1h+Z5AF4t3yP1mxNW7HL8qhPm8y4Uupp4b03QSC7puVrkkCaO1E1NQA9q9K
  artifact: rssguardexe, rssguard7z
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true

build_script:
  - git submodule update --init --recursive
  - set "QT_PLUGIN_PATH=%QTDIR%\plugins"
  - set "PATH=%QTDIR%\bin;%PATH%"
  - '%COMPILERBAT%'
  - dir
  - mkdir rssguard-build
  - cd rssguard-build
  - lrelease.exe -compress C:\rssguard\rssguard.pro
  - qmake.exe C:\rssguard "%qmake_args%"
  - nmake
  - nmake windows_all

on_success:
  - ps: .\..\resources\scripts\.appveyor-install-win.ps1