version: 3.3.{build}
skip_tags: true
image: Visual Studio 2013
clone_depth: 1
clone_folder: c:\rssguard

environment:
  QMAKESPEC: win32-msvc2013

build_script:
  - dir
  - "C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC\\vcvarsall.bat" x86
  - cd ..
  - mkdir rssguard-build
  - cd rssguard-build
  - C:\Qt\5.7\msvc2013\bin\qmake.exe C:\rssguard
  - nmake