version: 666.{build}
skip_tags: false
os: Visual Studio 2017
clone_depth: 1
clone_folder: C:\rssguard

environment:
  QTDIR: 'C:\Qt\5.9\msvc2017_64'
  QMAKESPEC: win32-msvc
  COMPILERBAT: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"'
  access_token:
    secure: bM8uJbH7GK+2EW6aL8D0/qwwdM/lzW6y2odXWs/VcMq+nUBZa68x+k3EpZEAo6iT
  matrix:
    - qmake_args: 'USE_WEBENGINE=false'
    - qmake_args: 'USE_WEBENGINE=true'

artifacts:
  - path: 'rssguard-build\*win64.exe'
    name: rssguardexe

  - path: 'rssguard-build\*win64.7z'
    name: rssguard7z

deploy:
  description: 'release by appveyor'
  provider: GitHub
  auth_token:
    secure: XCWdr9wPgK4gm6289WXCg2vtMA02eBSnj6eKHC+ps6Z5lgw0jsK09UQ5y9E9ZFwS # your encrypted token from GitHub
  artifact: rssguardexe, rssguard7z # upload all NuGet packages to release assets
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true        # deploy on tag push only

build_script:
  - git submodule update --init --recursive
  - set "QT_PLUGIN_PATH=%QTDIR%\plugins"
  - set "PATH=%QTDIR%\bin;%PATH%"
  - '%COMPILERBAT%'
  - dir
  - mkdir rssguard-build
  - cd rssguard-build
  - qmake.exe C:\rssguard "%qmake_args%"
  - nmake
  - nmake windows_all

on_success:
  - ps: ls
  - ps: git clone -q --depth=1 https://github.com/martinrotter/rssguard.wiki.git C:\rssguard-wiki
  - ps: git config --global credential.helper store
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
  - ps: git config --global user.email "rotter.martinos@gmail.com"
  - ps: git config --global user.name "martinrotter"
  - ps: $file = (Get-ChildItem '*.7z').Name
  - ps: echo "File to upload: $file"
  - ps: $url = curl.exe --upload-file "$file" "https://transfer.sh/$file" --silent
  - ps: echo "Obtained URL: $url"
  - ps: echo " from powershell $url " >> C:\rssguard-wiki\Windows-development-builds.md
  - ps: cd C:\rssguard-wiki
  - ps: git add *.*
  - ps: git commit -m "New files."
  - ps: git pull origin master
  - ps: git push origin master -v
