version: 3.3.{build}
skip_tags: true
image: Visual Studio 2013
clone_depth: 1
clone_folder: c:\rssguard
build_script:
- cmd: >-
    cd C:\
    mkdir rssguard-build
    cd rssguard-build
    C:\Qt\5.7\msvc2013\qmake C:\rssguard
    nmake