language: cpp
osx_image: xcode9.4
sudo: required
dist: xenial
os:
- linux
- osx
env:
- USE_WEBENGINE=false
- USE_WEBENGINE=true
compiler:
- gcc
notifications:
  email: false
deploy:
  - provider: releases
    file_glob: true
    skip_cleanup: true
    api_key: $GH_TOKEN
    file:
    - rssguard-build/src/rssguard/rss*.AppImage
    - rssguard-build/src/rssguard/rss*.dmg
    on:
      tags: true
      all_branches: true
  - provider: bintray
    file: .travis-bintray-desc.json
    user: martinrotter
    key: $BINTRAY_KEY
    skip_cleanup: true
    on:
      all_branches: true

git:
  submodules: false
  depth: 10
before_install: "./resources/scripts/.travis-before-install.sh"
install: true
script:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./resources/scripts/.travis-install-linux.sh
  ; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./resources/scripts/.travis-install-osx.sh
  ; fi
