language: cpp
osx_image: xcode7.3
sudo: required
dist: trusty

os:
  - linux
  - osx

compiler:
  - gcc
  
git:
  submodules: false
  depth: 3
  
before_install: ./.travis-before-install.sh

install: true
  
script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then source /opt/qt57/bin/qt57-env.sh ; fi
  - mkdir rssguard-build && cd rssguard-build
  - qmake ..
  - make
  - make install