dist: trusty

os:
  - linux
  
compiler:
  - gcc
  
before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt57-trusty
  - sudo apt-get update
  - sudo apt-get install qt57tools qt57base qt57webengine
  
qmake . && make