language: cpp
osx_image: xcode8
sudo: required
dist: trusty

os:
  - linux
  - osx

compiler:
  - gcc
  
git:
  submodules: false
  depth: 3
  
before_install: ./.travis-before-install.sh

install: true
  
script:
  - mkdir rssguard-build && cd rssguard-build
  - qmake ..
  - make
  - make install