language: cpp
osx_image: xcode7.3
sudo: required
dist: trusty
os:
- linux
- osx
env:
- USE_WEBENGINE=false
- USE_WEBENGINE=true
compiler:
- gcc
deploy:
  provider: releases
  api_key:
    secure: "$GH_TOKEN"
  file_glob: true
  file: "*.dmg"
  file: "*.AppImage"
  skip_cleanup: true
  on:
    tags: true
git:
  submodules: false
  depth: 40
before_install: "./resources/scripts/.travis-before-install.sh"
install: true
script:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./resources/scripts/.travis-install-linux.sh
  ; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./resources/scripts/.travis-install-osx.sh
  ; fi
