dist: trusty

language: cpp

os:
  - linux
  
compiler:
  - gcc
  
git:
  submodules: false
  depth: 3
  
before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt57-trusty -y
  - sudo apt-get update
  - sudo apt-get -y install qt57tools qt57base qt57webengine

install: true
  
script:
  - source /opt/qt57/bin/qt57-env.sh
  - mkdir rssguard-build && cd rssguard-build
  - qmake ..
  - make