dist: trusty
language: cpp
osx_image: xcode8

os:
  - linux
  - osx

compiler:
  - gcc
  
git:
  submodules: false
  depth: 3
  
before_install:
  - ./.travis-before-install.sh

install: true
  
script:
  - source /opt/qt57/bin/qt57-env.sh
  - mkdir rssguard-build && cd rssguard-build
  - qmake ..
  - make
  - make install